### ISSUE TITLE
Rotate the background image in the carousel

### ISSUE THREAD

**Issue by jules32** [Openscapes/website#1]
My website is made with [blogdown](https://bookdown.org/yihui/blogdown/), using the [hugo-universal-theme](https://themes.gohugo.io//theme/hugo-universal-theme/). The development url for the website is [here](https://sad-williams-fa509f.netlify.com/) so you can see what it looks like.

I am looking for some blogdown/netlify/CSS guidance. I am a novice tinkerer in this realm but know this is possible to do:

I've built the website using the awesome [hugo-universal-theme](https://themes.gohugo.io/theme/hugo-universal-theme/) and I would love help with the carousel feature that you see at the top of the home page. 

I would love for the carousel to rotate the background image along with the text. This is to display more of allisonhorst's art (currently displayed on the [about page](https://sad-williams-fa509f.netlify.com/about). If anyone would be able to help me do this or put me in contact with someone, that would be amazing. 

Thank you!

**Comment by jules32** [comment]
Additional notes from Alison Hill: 

If you want the full background image to rotate (rather than images over the background), you’ll need to edit the `carousel.html` widget, probably to rotate the `jumbotron` css class. 
If you want to see a theme that has a hero carousel widget (so where the full image rotates), check out the academic theme: https://github.com/gcushen/hugo-academic/issues/622

This looks like a good tutorial for how to change how the owl javascript widget works: https://webdesign.tutsplus.com/tutorials/how-to-build-a-full-screen-responsive-carousel-slider-with-owljs--cms-31771

**Comment by Pomax** [comment]
I had a quick look at the dev link, but I don't see a carousel, where would I be looking? (Also, the grasslands banner is a 17MB image so that's probably something you'll want to address. That's significantly bigger than most people can load, so it's worth bringing that down to a smaller resolution and filesize)

**Comment by jules32** [comment]
Thanks for looking at this @Pomax! 

Let's see.  I believe the carousel is created with owl.js ([tutorial](https://webdesign.tutsplus.com/tutorials/how-to-build-a-full-screen-responsive-carousel-slider-with-owljs--cms-31771) that I wasn't able to follow). The carousel in my website repo is called the `owl-carousel`. 

The way Hugo works is that anything in the root directory (e.g. ` website/layouts/partials/carousel.html` will be run first and have priority over anything in the themes directory (e.g. `https://github.com/Openscapes/website/tree/master/themes/hugo-universal-theme/layouts/partials/carousel.html` (also so that it's easier to see what's been updated from the template theme and allows for updates to be more smoothly incorporated). 

There is JS for it: 

[themes/hugo-universal-theme/static/js/owl.carousel.min.js](https://github.com/Openscapes/website/blob/master/themes/hugo-universal-theme/static/js/owl.carousel.min.js)

The CSS for it: is

- [themes/hugo-universal-theme/static/css/owl.carousel.css](https://github.com/Openscapes/website/blob/master/themes/hugo-universal-theme/static/css/owl.carousel.css)
- [themes/hugo-universal-theme/static/css/owl.theme.css](https://github.com/Openscapes/website/blob/master/themes/hugo-universal-theme/static/css/owl.theme.css)

**Comment by jules32** [comment]
After talking with Pomax about this we decided to not use the carousel on the website, and therefore I'm close this issue without doing it. We decided against it because carousels aren't great for accessibility (reading and loading). So this issue is no more!
