### ISSUE TITLE
Change the "breadcrumbs" images on single pages (CSS/Hugo) 

### ISSUE THREAD

**Issue by jules32** [Openscapes/website#3]
My website is made with [blogdown](https://bookdown.org/yihui/blogdown/), using the [hugo-universal-theme](https://themes.gohugo.io//theme/hugo-universal-theme/). The development url for the website is [here](https://sad-williams-fa509f.netlify.com/) so you can see what it looks like. My request pertains to the "breadcrumbs" banners on 4 pages: Champions Program, Resources, About, Get Involved.

These pages are all copies of the [default single page layout](https://github.com/Openscapes/website/blob/master/layouts/page/single.html#L16), which I am able to do by duplicating an `.md` file, for example [champions.md](https://github.com/Openscapes/website/blob/master/content/champions.md) and [resources.md](https://github.com/Openscapes/website/blob/master/content/resources.md). This gives the pages the same look but lets me have different content for the champions and resources pages. 

Now, I would like to change the image that runs across the top of each page. This is called "breadcrumbs". 

**I've outlined as far as I have gotten below, with 2 ideas for options including one that I tried, producing errors. I would really appreciate help in figuring this out!**

----

The breadcrumbs .png image is assigned in [style.default.css](https://github.com/Openscapes/website/blob/master/static/css/style.default.css#L1729) with a variable name `heading-breadcrumbs`. This is then called from the [breadcrumbs.html partial](https://github.com/Openscapes/website/blob/master/layouts/partials/breadcrumbs.html#L1). Looking at breadcrumbs.html, I see that it will execute the [`{{ .Title }}`](https://github.com/Openscapes/website/blob/master/layouts/partials/breadcrumbs.html#L5) variable, which it calls from the TOML information at the top of, for example, the [champions.md page](https://github.com/Openscapes/website/blob/master/content/champions.md).

The simplest option I can imagine would be to instead of defining the .png in the CSS file, I would define it in the TOML at the top of the champions.md file (e.g. "breadcrumbs = image.png"). This would mean retooling the CSS and breadcrumbs.html files, and I didn't know how to begin with that.

A second option that I expected would be possible would be to define a bunch of different `heading-breadcrumbs` versions (`heading-breadcrumbs2`, `heading-breadcrumbs3`...) in the CSS file, and call that from the TOML file that would be passed to the breadcrumbs.html file. This would look like this:

`champions.md`:
```
+++
title = "Champions Program"
description = "Champions Program"
breadcrumb = "heading-breadcrumbs"
+++
```

`breadcrumb.html`:
```
<div id="{{ .Breadcrumb }}">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{ .Title }}</h1>
            </div>
        </div>
    </div>
</div>
```

But this returned the error: 

```
Error: Error building site: failed to render pages: render of "page" failed: "/Users/lowndes/github/website/themes/hugo-universal-theme/layouts/_default/single.html:1:8": execute of template failed: template: _default/single.html:16:11: executing "_default/single.html" at <partial "breadcrumbs...>: error calling partial: "/Users/lowndes/github/website/layouts/partials/breadcrumbs.html:1:8": execute of template failed: template: partials/breadcrumbs.html:1:8: executing "partials/breadcrumbs.html" at <.Breadcrumb>: can't evaluate field Breadcrumb in type *hugolib.PageOutput
```

Thank you for your help!

**Comment by Pomax** [comment]
Rather than changing the `id`, I'd recommend changing https://github.com/Openscapes/website/blob/master/layouts/partials/breadcrumbs.html#L1 to `<div id="heading-breadcrumbs" data-title="{{ .Title }}">` so that you can then use CSS directly, using:
```
#heading-breadcrumbs[data-title='Champions Program'] {
    background-image: ...
    ...
}

#heading-breadcrumbs[data-title=Resources] {
    background-image: ...
    ...
}

...
```
That way your modification to the template only "adds" things to it, so they're easy to redo if necessary after an upgrade ("replacements" are much harder to redo), and you can put the CSS for this in its own file like "breadcrumb-overrides.css" and easily switch between original styling or your custom styling by adding it as a `<link rel="stylesheet" href="breadcrumb-overrides.css">` or by leaving it off.

**Comment by jules32** [comment]
Thanks @Pomax!

I've incorporated these edits in [this commit](https://github.com/Openscapes/website/commit/e9a516a0897f10179f77f7405febcdec8c3408bd) but think I am still missing something (the images haven't updated). 

Is there something I'm missing with what is a `data-title` and what is a `.Title`? 

The TOML for an example page [content/champions.md](https://raw.githubusercontent.com/Openscapes/website/master/content/champions.md) is:

```
+++
title = "Champions Program"
description = "Champions Program"
keywords = ["FAQ","How do I","questions","what if"]
+++
```

**Comment by jules32** [comment]
Solved thanks to @Pomax!

Documenting what we did in a series of commits (starting with [this one](https://github.com/Openscapes/website/commit/0676fef8d284d016a302f5e657966382e971ddb4)) (and screenshot below): 

1. Created  static/css/breadcrumbs-overrides.css which has the following *with no additional CSS styling*:
  ```#heading-breadcrumbs[data-title='Champions Program'] {
  background-image: url('../img/horst_openscapes_mountains_texture.png')
}

#heading-breadcrumbs[data-title=Resources] {
  background-image: url('../img/horst_openscapes_desert_tortoise.png') 
}
```
2. layouts/partials/head.html *with the css/ folder explicit*:

```
  <!-- Custom stylesheet - for your changes -->
  <link href="{{ "css/breadcrumbs-overrides.css" | relURL}}" rel="stylesheet">
```

3. layouts/partials/breadcrumbs.html line 1: 

```
<div id="heading-breadcrumbs" data-title="{{ .Title }}">
```

And troubleshooting: 
- on the website, right-click Inspect Element
- Network > CSS
  - **is it there?** not showing up? How about in Other? 404 error: that was because head.html's filepath was wrong
  - showing up: **what's in it?** right-click > open in new tab: looks like what I wrote, so start tinkering with the CSS, that's how I learned what I added as `margin-bottom` and `padding` was causing trouble. 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/5891909/50932476-96031380-141a-11e9-9e1f-cc35d74f953c.png">
