### ISSUE TITLE
Ileana's bio missing a word

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/website#45]
@IleanaF it looks like a word is missing from this sentence in [your bio](https://www.openscapes.org/team/)

> Her work uses innovative quantitative to improve ...

I'm happy to update it on the website (or if you prefer, you could make a pull request)

**Comment by IleanaF** [comment]
Hi Stef! Thank you for catching that! the next word should be "methods". Also, if appropriate, I don't have a personal website updated currently but if you all would like to link my Linkedin or Twitter that would be alright with me! Thank you! 

Linkedin : https://www.linkedin.com/in/ileana-fenwick-0238ba132/
Twitter: https://twitter.com/_ileanaf 
@stefaniebutland

**Comment by jules32** [comment]
Thank you for updating @stefaniebutland !

When you do so, can you please also add Ileana's talk to the presentations section of https://github.com/Openscapes/website/blob/main/content/media.md? 

(and a reminder to watch for /'s from the visual editor for now :))
